import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { FormEventHandler, useMemo, useState } from 'react';

type Item = { id: number; code: string; epic: string; title: string; description: string | null; priority: string; status: string; release: string | null; points: number | null };
type Project = { id: number; name: string; code: string; description: string | null; status: string };
const statuses: Record<string, string> = { pending: 'Pendente', in_progress: 'Em andamento', validation: 'Em validação', done: 'Concluído' };

export default function Backlog({ project, items }: { project: Project; items: Item[] }) {
    const [showForm, setShowForm] = useState(false); const [filter, setFilter] = useState('all');
    const { data, setData, post, processing, errors, reset } = useForm({ code: '', epic: '', title: '', description: '', priority: 'P1', release: 'R1', points: '' });
    const visible = useMemo(() => filter === 'all' ? items : items.filter((item) => item.status === filter), [filter, items]);
    const submit: FormEventHandler = (event) => { event.preventDefault(); post(route('projects.backlog.store', project.id), { onSuccess: () => { reset(); setShowForm(false); } }); };
    const changeStatus = (item: Item, status: string) => router.patch(route('projects.backlog.status', [project.id, item.id]), { status }, { preserveScroll: true });
    return <AuthenticatedLayout header={<div><Link href={route('projects.index')} className="text-sm font-medium text-indigo-600 hover:text-indigo-700">← Projetos</Link><h2 className="mt-1 text-2xl font-semibold text-slate-900">{project.name}</h2></div>}>
        <Head title={`${project.code} — Backlog`} />
        <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-xl bg-slate-900 p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-300">{project.code}</p><p className="mt-2 max-w-2xl text-sm text-slate-300">{project.description || 'Backlog do projeto.'}</p></div><button onClick={() => setShowForm(!showForm)} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-900 hover:bg-indigo-50">Adicionar item</button></div><div className="mt-6 flex gap-8 text-sm"><span><b className="text-xl">{items.length}</b> itens</span><span><b className="text-xl">{items.filter((item) => item.status === 'done').length}</b> concluídos</span><span><b className="text-xl">{items.filter((item) => item.priority === 'P0').length}</b> críticos</span></div></div>
        {showForm && <form onSubmit={submit} className="my-6 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-3"><label className="text-sm font-medium text-slate-700">Código<input value={data.code} onChange={(e) => setData('code', e.target.value.toUpperCase())} placeholder="BL-01-01" className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /></label><label className="text-sm font-medium text-slate-700">Épico<input value={data.epic} onChange={(e) => setData('epic', e.target.value)} placeholder="01 Plataforma" className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /></label><label className="text-sm font-medium text-slate-700">Prioridade<select value={data.priority} onChange={(e) => setData('priority', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></label><label className="text-sm font-medium text-slate-700 md:col-span-2">Funcionalidade<input value={data.title} onChange={(e) => setData('title', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /><span className="text-xs text-red-600">{errors.title || errors.code}</span></label><label className="text-sm font-medium text-slate-700">Release<input value={data.release} onChange={(e) => setData('release', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" /></label><label className="text-sm font-medium text-slate-700 md:col-span-3">Descrição<textarea value={data.description} onChange={(e) => setData('description', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" rows={2} /></label><div className="md:col-span-3"><button disabled={processing} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Salvar item</button></div></form>}
        <div className="my-6 flex flex-wrap gap-2">{[['all','Todos'],['pending','Pendentes'],['in_progress','Em andamento'],['validation','Validação'],['done','Concluídos']].map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-1.5 text-sm font-medium ${filter === value ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{label}</button>)}</div>
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Item</th><th className="px-4 py-3">Prioridade</th><th className="px-4 py-3">Release</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((item) => <tr key={item.id}><td className="px-4 py-4"><p className="text-xs font-semibold text-indigo-600">{item.code} · {item.epic}</p><p className="mt-1 font-medium text-slate-900">{item.title}</p>{item.description && <p className="mt-1 text-sm text-slate-500">{item.description}</p>}</td><td className="px-4 py-4 align-top"><span className={`rounded px-2 py-1 text-xs font-bold ${item.priority === 'P0' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{item.priority}</span></td><td className="px-4 py-4 align-top text-sm text-slate-600">{item.release || '—'}</td><td className="px-4 py-4 align-top"><select value={item.status} onChange={(e) => changeStatus(item, e.target.value)} className="rounded-lg border-slate-300 text-sm">{Object.entries(statuses).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></td></tr>)}{visible.length === 0 && <tr><td colSpan={4} className="px-4 py-10 text-center text-sm text-slate-500">Nenhum item neste filtro.</td></tr>}</tbody></table></div></div>
    </AuthenticatedLayout>;
}
