import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { FormEventHandler, useMemo, useState } from 'react';

type Item = { id: number; code: string; epic: string; title: string; description: string | null; priority: string; status: string; release: string | null; points: number | null };
type Project = { id: number; name: string; code: string; description: string | null; status: string };
type BacklogData = { id: number; code: string; name: string; description: string | null; status: string; items_count: number; tasks_count: number };
const statuses: Record<string, string> = { pending: 'Pendente', in_progress: 'Em andamento', validation: 'Em validação', done: 'Concluído' };

export default function Backlog({ project, backlog, items }: { project: Project; backlog: BacklogData; items: Item[] }) {
    const [showForm, setShowForm] = useState(false);
    const [filter, setFilter] = useState('all');
    const { data, setData, post, processing, errors, reset } = useForm({ code: '', epic: '', title: '', description: '', priority: 'P1', release: 'R1', points: '' });
    const visible = useMemo(() => filter === 'all' ? items : items.filter((item) => item.status === filter), [filter, items]);
    const submit: FormEventHandler = (event) => { event.preventDefault(); post(route('projects.backlog.items.store', [project.id, backlog.id]), { onSuccess: () => { reset(); setShowForm(false); } }); };
    const changeStatus = (item: Item, status: string) => router.patch(route('projects.backlog.items.status', [project.id, backlog.id, item.id]), { status }, { preserveScroll: true });

    return <AuthenticatedLayout header={<div className="flex flex-wrap items-center justify-between gap-3"><div><Link href={route('projects.backlog.index', project.id)} className="text-sm font-medium text-indigo-600 hover:text-indigo-700">← Backlogs de {project.name}</Link><h2 className="mt-1 text-2xl font-semibold text-slate-900">{backlog.name}</h2><p className="mt-1 text-sm text-slate-500">{project.code} · {backlog.code}</p></div><div className="flex gap-2"><button onClick={() => setShowForm(!showForm)} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Adicionar item</button><Link href={route('projects.timeline.index', [project.id, backlog.id])} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">Abrir Gantt</Link></div></div>}>
        <Head title={`${backlog.code} — ${backlog.name}`} />
        <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
            <section className="mb-6 rounded-xl bg-slate-900 p-6 text-white"><p className="max-w-3xl text-sm text-slate-300">{backlog.description || 'Itens e entregas organizados neste backlog.'}</p><div className="mt-5 flex gap-8 text-sm"><span><b className="text-xl">{items.length}</b> itens</span><span><b className="text-xl">{items.filter((item) => item.status === 'done').length}</b> concluídos</span><span><b className="text-xl">{backlog.tasks_count}</b> tarefas no Gantt</span></div></section>
            {showForm && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-3"><label className="text-sm font-medium text-slate-700">Código<input value={data.code} onChange={(e) => setData('code', e.target.value.toUpperCase())} placeholder="BL-01-01" className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /><span className="text-xs text-red-600">{errors.code}</span></label><label className="text-sm font-medium text-slate-700">Épico<input value={data.epic} onChange={(e) => setData('epic', e.target.value)} placeholder="01 Plataforma" className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /></label><label className="text-sm font-medium text-slate-700">Prioridade<select value={data.priority} onChange={(e) => setData('priority', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select></label><label className="text-sm font-medium text-slate-700 md:col-span-2">Funcionalidade<input value={data.title} onChange={(e) => setData('title', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required /><span className="text-xs text-red-600">{errors.title}</span></label><label className="text-sm font-medium text-slate-700">Release<input value={data.release} onChange={(e) => setData('release', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" /></label><label className="text-sm font-medium text-slate-700 md:col-span-3">Descrição<textarea value={data.description} onChange={(e) => setData('description', e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" rows={2} /></label><div className="md:col-span-3"><button disabled={processing} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Salvar item</button></div></form>}
            <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Itens do backlog</h2><p className="mt-1 text-sm text-slate-500">As tarefas detalhadas e dependências ficam no Gantt deste backlog.</p></div><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-lg border-slate-200 text-sm" aria-label="Filtrar itens por status"><option value="all">Todos os status</option>{Object.entries(statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="divide-y divide-slate-100">{visible.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="text-xs font-semibold text-indigo-600">{item.code} · {item.epic} · {item.priority}</p><h3 className="mt-1 font-medium text-slate-900">{item.title}</h3>{item.description && <p className="mt-1 text-sm text-slate-500">{item.description}</p>}</div><div className="flex items-center gap-3"><span className="text-xs text-slate-500">{item.release || 'Sem release'}</span><select value={item.status} onChange={(event) => changeStatus(item, event.target.value)} className="rounded-lg border-slate-200 text-sm" aria-label={`Status de ${item.title}`}>{Object.entries(statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></article>)}{visible.length === 0 && <p className="px-6 py-12 text-center text-sm text-slate-500">{items.length ? 'Nenhum item corresponde ao filtro.' : 'Este backlog ainda não tem itens cadastrados.'}</p>}</div></section>
        </div>
    </AuthenticatedLayout>;
}
